---
# tasks file for code deploy
- name: Update apt cache
  apt: update_cache=yes

- name: Install git
  apt: name={{ item }} state=present
  with_items:
    - git
    - ntp

- name: Install pip
  apt: name=python-pip state=present

- name: Install pip packages
  pip: name={{ item }} state=present
  with_items:
    - Flask
    - jsonify
    - requests
    - Flask-Dance
    - gunicorn
    - supervisor

- name: Create dir 
  file: 
    path: '{{ working_dir }}'
    state: directory 
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Clone the repo
  git:
    repo: 'https://bitbucket.org/azneita/devops-challenge.git'
    dest: '{{ app_dir }}'
  become_user: '{{ user }}'


- name: Setup supervisor  script
  template:
    src: supervisord.conf.j2
    dest: "{{ working_dir }}/{{ inventory_hostname }}.conf"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
  become_user: '{{ user }}'

- name: Start supervisord
  command: supervisord -c "{{ working_dir }}/{{ inventory_hostname }}.conf"
  become_user: '{{ user }}'
# - name: Start upstart script 
#   service:
#     name: "{{ inventory_hostname }}"
#     state: started

- name: Check the status of the app 
  uri:
    url: http://127.0.0.1:5000
    status_code: 200
    timeout: 300
  async: 300
  poll: 10  