---
# tasks file for code deploy
- name: Update apt cache
  apt: update_cache=yes

- name: Install system packages
  apt: name={{ item }} state=present
  with_items:
    - python-pip
    - git
    - ntp

- name: Add the user 'cody' as  'developers' to the user's groups
  user:
    name: '{{ user }}'
    shell: /bin/bash

- name: Install pip packages
  pip: name={{ item }} state=present
  with_items:
    - Flask
    - jsonify
    - requests
    - Flask-Dance
    - gunicorn
    - supervisor

- name: Create dir 
  file: 
    path: '{{ working_dir }}'
    state: directory 
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Create log dir 
  file: 
    path: '{{ app_log_dir }}'
    state: directory 
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Clone the repo
  git:
    repo: 'https://bitbucket.org/azneita/devops-challenge.git'
    dest: '{{ app_dir }}'
  become_user: '{{ user }}'


- name: Setup supervisor  script
  template:
    src: supervisord.conf.j2
    dest: "{{ working_dir }}/{{ inventory_hostname }}.conf"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
  become_user: '{{ user }}'

- name: Setup startup  script
  template:
    src: startup.sh.j2
    dest: "{{ working_dir }}/startup.sh"
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: a+x
  become_user: '{{ user }}'

- name: copy  upstart script to init 
  template:
    src: "supervisor_upstart.conf.j2"
    dest: "/etc/init/{{ inventory_hostname }}.conf"
    owner: root
    group: root
    mode: 0644
  register: script_copied

- name: Start upstart script 
  service:
    name: "{{ inventory_hostname }}"
    state: started
  register: process_started

- name: Wait for port
  wait_for:
     port: 5000
     delay: 10

- name: Check the status of the app 
  uri:
    url: http://127.0.0.1:5000
    status_code: 200
    timeout: 500
  async: 300
  poll: 10
  #when: process_started.changed  